rm(list=ls())
library(RODBC)
library(tidyverse)
library(sp)
library(rgdal)
library(rgeos)
mdbConnect<-odbcDriverConnect("Driver={Microsoft Access Driver (*.mdb)};DBQ=M:/ItoN/MidnightSunTrinityJV/Modeling/AFP6/Analytical Data/AFP06.mdb")
mdbConnect<-odbcConnectAccess("M:/ItoN/MidnightSunTrinityJV/Modeling/AFP6/Analytical Data/AFP06.mdb")
LDI<-sqlFetch(mdbConnect, "LDI")